<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'order_type' => 'asc',
  'list_type' => 'win',
  'list_num' => '9',
  'auto_finish' => '1',
  'index_slide' => 'a:3:{i:0;a:3:{s:4:"name";s:120:"红酥手，黄縢酒，满城春色宫墙柳。东风恶，欢情薄，一怀愁绪，几年离索。错！错！错！";s:3:"url";s:13:"www.zhihu.com";s:3:"img";s:39:"upload/2014/08/21/20140821041949304.jpg";}i:1;a:3:{s:4:"name";s:48:"春如旧，人空瘦，泪痕红浥鲛绡透。";s:3:"url";s:12:"www.zhiu.con";s:3:"img";s:39:"upload/2014/08/21/20140821042211465.jpg";}i:2;a:3:{s:4:"name";s:72:"桃花落，闲池阁，山盟虽在，锦书难托。莫！莫！莫！";s:3:"url";s:13:"www.baidu.com";s:3:"img";s:39:"upload/2014/08/21/20140821042211510.jpg";}}',
  'name' => '转易网',
  'url' => 'http://www.jooyea.cn',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class=\\"footer\\">	<p class=\\"links\\">		<a href=\\"\\">关于我们</a>|<a href=\\"\\">常见问题</a>|<a href=\\"\\">安全交易</a>|<a href=\\"\\">购买流程</a>|<a href=\\"\\">如何付款</a>|<a href=\\"\\">联系我们</a>|<a href=\\"\\">合作提案</a> 	</p>	<p class=\\"copyright\\">		Powered by <a href=\\"http://www.zhuanyiwang.cn\\">转易网</a> 	</p>Copyright © 2005-2014 <a class=\\"copyys\\" target=\\"_blank\\" href=\\"%E5%BE%85%E8%AE%BE%E7%BD%AE\\">滇ICP备01000010号</a> </div>',
  'tax' => '10',
  'stockup_time' => '1',
  'regiment_time_limit' => '60',
  'index_seo_title' => '',
  'index_seo_keywords' => '',
  'index_seo_description' => '',
  'goods_no_pre' => 'SD',
)?>